spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    # 默认innodb引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jblog?characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=PRC
    username: root
    password:
  resources:
    # 静态目录，增加图片的目录
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${blog.upload.image.storage}

  # session
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: "jblog:spring:session"

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

  # 模板配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

# shiro
shiro:
  loginUrl: "/login"

# 博客项目配置
blog:
  index:
    page-size: 30
  member:
    page-size: 10

  # 用户相关配置
  user:
    defaultAvatar: "/assets/images/default-avatar.png"

  # 服务配置
  services:
    # 阿里云服务
    aliyun:
      # 邮件配置
      email:
        access_key: ""
        access_secret: ""
        area: "cn-hangzhou"
        from: ""
        account: ""

  # 上传配置
  upload:
    image:
      storage: "/Users/xiaoteng/IdeaProjects/blog/public/images"
      size: 1024
      mimes:
        - "image/png"
        - "image/gif"
        - "image/jpg"
        - "image/jpeg"