spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    # 默认innodb引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jblog?characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=PRC
    username: root
    password:

  # session
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: "jblog:spring:session"

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

  # 模板配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

# shiro
shiro:
  loginUrl: "/login"

# 博客项目配置
blog:
  index:
    page-size: 20